### ISSUE TITLE
check-es-query-count fails on Elasticsearch6

### ISSUE THREAD

**Issue by stefan-as** [sensu-plugins/sensu-plugins-elasticsearch#103]
Seems like Elasticsearch6 refuses `application/x-www-form-urlencoded` http queries:
```
# check-es-query-count.rb  --query "*" --offset 15552000 --months-previous 1 --crit 0
Check failed to run: [406] {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
```

**Comment by majormoses** [comment]
Thanks for reporting this, do you think you would have the time to try adding an option to allow specifying the content type?

**Comment by shankerbalan** [comment]
Hi @majormoses,

Since am running into the same issue after an upgrade, what should be the content type that needs to be set?

@shankerbalan

**Comment by eheydrick** [comment]
It should be set to `Content-Type: application/json`. ES6 does [strict content-type checking](https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests).

**Comment by majormoses** [comment]
Sorry I missed this but yes pretty much everything dealing with es uses json.

**Comment by alexandrustaetu** [comment]
Hello,

Looks like this is fixed with with https://github.com/elastic/elasticsearch-ruby/commit/76f86793cde0a0e7e816a743c73f69002a53483e#diff-b1922392c370e21793167c8dafa56a62. Because sensu-plugins-elasticsearch uses aws-es-transport ( https://rubygems.org/gems/aws-es-transport/versions/0.1.4 ) which depends on elasticsearch >= 1.0.10, ~> 1.0, the above fix cannot be used ( elasticsearch-ruby 5 ).

In order to be compatible with ES6 api, we can allow passing headers from the cli in a comma-separated list ( ex: --header='Content-Type: application/json' )

Added a pull request for this issue/new feature here https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/111.

Not sure if this should be merged to master or to tag, let me know if the pull request needs to be re-created.

Thanks,
Alex.

**Comment by stefan-as** [comment]
Works for me with version 2.0.1.
